### ISSUE TITLE
Problemas iniciando um jogo localmente

### ISSUE THREAD

**Issue by falcao-g** [lugobots/the-dummies-js#13]
Olá pessoal, gostaria de dizer que eu gostei bastante da ideia do site! 

Mas estou com alguns problemas ao fazer a minha partida local iniciar, a história é a seguinte:

Eu nunca tinha mexido com docker antes, ontem eu baixei para testar o the-dummies-py e tomei um erro dizendo que minha porta 5000 estava ocupada, tudo bem, eu só mudei a propriedade `ports` para usar a porta 4000:

```yaml
    ports:
      - "4000:4000"
      - "8080:8080"
```

Depois disso ele executou perfeitamente!

Porém então eu decidi testar o the-dummies-js, e depois de testar sem e com essa modificação, nenhum dos dois times carregavam e eu tomei vários erros

Como eu não entendo muito de docker, eu não sei muito o que fazer para consertar, testei mudar a propriedade do time AWAY para ficar igual o arquivo de python, que funcionava, só tirando o serviço builder que não existe em js, então ficou:

```yaml
  player_01:
    image: node:18
    working_dir: /app
    command: npm run start
    depends_on:
      game_server:
        condition: service_healthy
      watcher:
        condition: service_healthy
    volumes:
      - "./:/app"
    network_mode: "host"
    environment:
      - BOT_NUMBER=1
      - BOT_TEAM=home
      - BOT_GRPC_URL=game_server:5000
  player_02:
    image: node:18
    working_dir: /app
    command: npm run start
    depends_on:
      game_server:
        condition: service_healthy
      watcher:
        condition: service_healthy
    volumes:
      - "./:/app"
    network_mode: "host"
    environment:
      - BOT_NUMBER=2
      - BOT_TEAM=home
      - BOT_GRPC_URL=game_server:5000
```
e assim por diante

Essa alteração consertou o time AWAY que agora carrega todo e aparece no meu campo, mas meu time home ainda não aparece, segue uma parte do meu terminal:
<img width="746" alt="image" src="https://github.com/lugobots/the-dummies-js/assets/60127788/44e2fd4d-b555-4e45-9076-5c7751cfa4ab">

Após isso tudo cai 

Fora as alterações especificadas aqui, o resto está igual ao repositório, alguém sabe o que tem de errado?
